; Inno Setup script for LecturePack.
; Produces LecturePack-Setup-<version>.exe with Start Menu + optional desktop
; shortcut, an app icon, and an uninstaller. The build script passes the
; version in via /DAppVersion=x.y.z so this stays in sync with version.py.

#ifndef AppVersion
  #define AppVersion "2.1.2"
#endif

; D-23: build.py passes /DSourceDir and /DOutputDir as already-normalized,
; absolute paths so ISCC never has to concatenate a "..\" segment onto its
; own script directory (app\packaging\) to find dist\LecturePack. That extra
; 13-character prefix pushed several bundled torch licence files past
; Windows' 260-char MAX_PATH and silently aborted the build with no
; Setup.exe produced. The relative defaults below only apply when ISCC is
; invoked manually without those defines.
#ifndef SourceDir
  #define SourceDir "..\dist\LecturePack"
#endif
#ifndef OutputDir
  #define OutputDir "..\dist\installer"
#endif

#define AppName "LecturePack"
#define AppPublisher "LecturePack"
#define AppExeName "LecturePack.exe"
#define AppURL "https://github.com/pasttrunks/lecturepack"
; D-20: must match APP_USER_MODEL_ID in app/desktop/main.py byte-for-byte,
; and stay free of any version component -- a version bump must never
; orphan a pinned taskbar or Start Menu icon. Defined once here and
; referenced by both non-uninstall [Icons] entries below so the two
; shortcut lines cannot drift from each other or from main.py's literal.
#define AppUserModelID "LecturePack.LecturePack"

[Setup]
AppId={{9F5D2E31-7C4A-4B8E-9E1D-LECTUREPACK01}}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}/releases
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; Per-user install by default → no admin prompt, and the silent auto-updater
; can replace files without elevation.
PrivilegesRequired=lowest
OutputDir={#OutputDir}
OutputBaseFilename=LecturePack-{#AppVersion}-Setup
SetupIconFile=lecturepack.ico
AppCopyright=LecturePack

; ---- Wizard branding -------------------------------------------------------
; The installer is the first thing a student sees of LecturePack, and it used
; to be Inno's stock blue-and-white artwork. These are the app's own mark on
; the app's own dark shell colour, generated by make_wizard_images.py from the
; same proportions make_icon.py uses, so the setup window, the taskbar icon and
; the app are recognisably one product.
;
; EVERY SIZE IS SUPPLIED NATIVELY, and that is functional rather than fussy:
; Inno's Setup binary is only system DPI aware (BUG-67), so anything it is not
; given at the right size gets resampled, and the banner is the largest thing
; in the window. Inno picks the closest match from each list.
;
; Only the banner and the header icon can be themed this way -- the wizard's
; own body is drawn with system colours, so the panel stays light. A fully dark
; wizard needs a custom VCL style (.vsf), which cannot be authored from this
; toolchain; do not spend time trying to force it with colour directives.
WizardImageFile=wizard-large-164x314.bmp,wizard-large-192x386.bmp,wizard-large-205x393.bmp,wizard-large-246x471.bmp,wizard-large-273x525.bmp,wizard-large-328x628.bmp
WizardSmallImageFile=wizard-small-55x58.bmp,wizard-small-64x68.bmp,wizard-small-69x73.bmp,wizard-small-83x88.bmp,wizard-small-92x97.bmp,wizard-small-110x116.bmp
; The images are already the exact sizes Inno asks for, so stretching them
; could only soften them. The back colour fills any remainder at a scaling
; factor between two of the supplied sizes, and matches app.css --bg (#16191F)
; written the way Inno wants it, $BBGGRR.
WizardImageStretch=no
WizardImageBackColor=$1F1916
; Modern style hides the welcome page by default, which is where the banner
; lives. It is one extra click and it is the only page that introduces the app.
DisableWelcomePage=no
UninstallDisplayIcon={app}\{#AppExeName}
#if Defined(FastCompression)
Compression=lzma2/fast
SolidCompression=no
#else
Compression=lzma2/max
SolidCompression=yes
#endif
WizardStyle=modern
; BUG-67: the "Select Additional Tasks" page rendered with the desktop-shortcut
; checkbox caption clipped and running into the group label above it, on a
; laptop running 2.1.1. It does NOT reproduce at 96 DPI -- the page was driven
; and captured there and is correct -- so this is a scaling failure.
;
; The cause is in Inno's own Setup binary, not in this script: its manifest
; declares <dpiAware>true</dpiAware> and nothing else. That is SYSTEM DPI
; awareness only -- there is no <dpiAwareness>PerMonitorV2</dpiAwareness> -- so
; the wizard is laid out for the DPI in force when the process started, and
; Windows bitmap-scales it afterwards. Fonts then no longer fit the control
; rectangles that were measured for them, which is exactly the reported
; symptom. No .iss directive can change that manifest.
;
; What this script CAN do is stop the page being sized to the millimetre.
; WizardSizePercent gives every caption headroom over its measured width, which
; is Inno's own documented remedy for "the text does not fit". (WizardResizable
; was tried here too and is NOT set: this Inno version warns that it is
; obsolete and ignored -- the wizard is resizable regardless. Do not add it
; back; it compiles to a warning and nothing else.)
;
; NOT confirmed on the reporter's machine. Do not close BUG-67 on this commit.
WizardSizePercent=120
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; Clear the previous build's payload BEFORE installing this one.
;
; [Files] copies over the top with `ignoreversion`, which updates and adds but
; never REMOVES. So any file an older version shipped and this one does not
; survived the upgrade forever. That is not cosmetic: upgrading 2.0.2 -> 2.0.3
; left 12 stale packages in the frozen sidecar (Cryptodome, certifi,
; cryptography, websockets, pywin32, yaml, brotli) and the leftovers broke
; `import yt_dlp`, so link import died on upgrade while a FRESH install of the
; same build was perfectly healthy. Caught by scripts/updater_ab_acceptance.py;
; a fresh-install test alone can never catch this class of bug.
;
; Only directories this installer fully re-ships are listed. User data lives in
; LecturePackData, never under {app}, so nothing here can touch it.
Type: filesandordirs; Name: "{app}\resources\LecturePackSidecar"
Type: filesandordirs; Name: "{app}\resources\ui"
Type: filesandordirs; Name: "{app}\resources\assets"
Type: filesandordirs; Name: "{app}\locales"

; NOTE: this section was silently lost once between 2.0.3 and 2.0.4 when an
; unrelated edit rewrote this file. tests/test_installer_iscc_path.py now
; asserts it is present -- do not delete it without reading DEF-019 in
; BUG_LIST.md first.

[Files]
; PyInstaller onedir output → everything under dist\LecturePack.
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; AppUserModelID: "{#AppUserModelID}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon; AppUserModelID: "{#AppUserModelID}"
; Explorer "Send to -> LecturePack". {usersendto} is the per-user SendTo folder
; so this needs no elevation and is removed with the rest of [Icons] on
; uninstall. Explorer passes the selected file paths as command-line
; arguments; LecturePack already forwards those to a running instance via
; its single-instance lock (see production-main.js 'second-instance'), so
; sending a lecture imports it instead of starting a second copy. The
; original file is only ever read.
Name: "{usersendto}\{#AppName}"; Filename: "{app}\{#AppExeName}"; AppUserModelID: "{#AppUserModelID}"

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent
